import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './app/View/Components/**/*.php',
    ],
    theme: {
        extend: {
            colors: {
                'tvip-blue': '#0f4c81',
                'tvip-blue-dark': '#0a3254',
                'tvip-blue-light': '#1a6ab3',
                'tvip-heading': '#101828',
                'tvip-strong': '#1e2939',
                'tvip-body': '#4a5565',
                'tvip-nav': '#364153',
                'tvip-label': '#364153',
                'tvip-muted': '#6a7282',
                'tvip-placeholder': '#717182',
                'tvip-disabled': '#99a1af',
                'tvip-black': '#000000',
                'tvip-cta-secondary': '#333333',
                'tvip-light-card': '#ecf5ff',
                'tvip-light-section': '#e6eef5',
                'tvip-surface': '#f9fafb',
                'tvip-social-bg': '#f3f4f6',
                'tvip-outline': '#d1d5dc',
                'tvip-divider': '#e5e7eb',
                'tvip-required': '#fb2c36',
                'tvip-hiring': '#ffd11a',
                'tvip-on-dark-muted': '#bedbff',
                'tvip-badge-blue-bg': '#dbeafe',
                'tvip-badge-blue': '#1447e6',
                'tvip-badge-green-bg': '#dcfce7',
                'tvip-badge-green': '#008236',
                'tvip-badge-red-bg': '#ffe2e2',
                'tvip-badge-red': '#c10007',
                'tvip-badge-indigo-bg': '#e0e7ff',
                'tvip-badge-indigo': '#432dd7',
                'tvip-badge-orange-bg': '#ffedd4',
                'tvip-badge-orange': '#ca3500',
                'tvip-success': '#008236',
                'tvip-success-bright': '#00c950',
                'tvip-success-bg': '#f0fdf4',
                'tvip-success-border': '#b9f8cf',
                'tvip-info-bg': '#eff6ff',
                'tvip-info-border': '#bedbff',
                'tvip-warning': '#a65f00',
                'tvip-warning-bg': '#fefce8',
                'tvip-warning-border': '#fff085',
            },
            fontFamily: {
                inter: ['Inter', 'sans-serif'],
            },
            borderRadius: {
                'tvip-hero': '40px',
                'tvip-card-lg': '24px',
                'tvip-card': '16px',
                'tvip-candidate': '14px',
                'tvip-button': '8px',
                'tvip-button-lg': '10px',
                'tvip-full': '9999px',
            },
            boxShadow: {
                'tvip-hero': '0px 25px 50px -12px rgba(0,0,0,0.25)',
                'tvip-floating': '0px 10px 7.5px rgba(0,0,0,0.1), 0px 4px 3px rgba(0,0,0,0.1)',
                'tvip-info-card': '0px 16px 32px -4px rgba(12,12,13,0.1), 0px 4px 4px -4px rgba(12,12,13,0.05)',
                'tvip-contact': '0px 1px 1.5px rgba(0,0,0,0.1), 0px 1px 1px rgba(0,0,0,0.1)',
                'tvip-navbar': '0px 1px 1.5px rgba(0,0,0,0.1), 0px 1px 1px rgba(0,0,0,0.1)',
                'tvip-job': '0px 1px 3px rgba(0,0,0,0.1), 0px 1px 2px -1px rgba(0,0,0,0.1)',
                'tvip-active': '0px 4px 3px rgba(0,0,0,0.1), 0px 2px 2px rgba(0,0,0,0.1)',
                'tvip-cta': '0px 10px 15px -3px rgba(0,0,0,0.1), 0px 4px 6px -4px rgba(0,0,0,0.1)',
                'tvip-auth': '0px 25px 25px rgba(0,0,0,0.25)',
                'tvip-overlay': '0px 25px 50px -12px rgba(0,0,0,0.25)',
            },
            backgroundImage: {
                'tvip-primary': 'linear-gradient(to right, #0a3254, #0f4c81)',
                'tvip-hero': 'linear-gradient(90deg, #0a3254 0%, #0f4c81 60%, #1a6ab3 100%)',
            },
            maxWidth: {
                'tvip-content': '1280px',
                'tvip-profile': '1024px',
            },
            zIndex: {
                nav: '400',
                backdrop: '500',
                dialog: '600',
                sheet: '700',
                toast: '900',
            },
        },
    },
    plugins: [forms],
};
